Repository Team-Going/Going-Server, pull requests merged in 2024-02, with the labels that each got.

#120 [feat] 회원가입 이벤트 디스코드 웹훅 기능 구현
  doorip-api/src/main/java/org/doorip/user/service/UserService.java
  doorip-common/src/main/java/org/doorip/message/ErrorMessage.java
  doorip-common/src/main/java/org/doorip/message/EventMessage.java
  doorip-external/src/main/java/org/doorip/openfeign/discord/DiscordFeignClient.java
  doorip-external/src/main/java/org/doorip/openfeign/discord/DiscordMessage.java
  doorip-external/src/main/java/org/doorip/openfeign/discord/DiscordMessageProvider.java
Labels: feat, 선웅

#122 [release] v1.1.0 릴리즈
  README.md
  doorip-api/src/main/java/org/doorip/user/service/UserService.java
  doorip-common/src/main/java/org/doorip/message/ErrorMessage.java
  doorip-common/src/main/java/org/doorip/message/EventMessage.java
  doorip-external/src/main/java/org/doorip/openfeign/discord/DiscordFeignClient.java
  doorip-external/src/main/java/org/doorip/openfeign/discord/DiscordMessage.java
  doorip-external/src/main/java/org/doorip/openfeign/discord/DiscordMessageProvider.java
Labels: 선웅, release

#125 [feat] 여행 정보 수정 API 구현
  doorip-api/src/main/java/org/doorip/trip/api/TripApiController.java
  doorip-api/src/main/java/org/doorip/trip/dto/request/TripUpdateRequest.java
  doorip-api/src/main/java/org/doorip/trip/service/TripService.java
  doorip-domain/src/main/java/org/doorip/trip/domain/Trip.java
Labels: feat, 정원
