Repository Team-Going/Going-Server, pull requests merged in 2024-01, with the labels that each got.

#5 [feat] Spring Security & JWT 설정
  doorip-api/build.gradle
  doorip-api/src/main/java/org/doorip/auth/ExceptionHandlerFilter.java
  doorip-api/src/main/java/org/doorip/auth/JwtAuthenticationEntryPoint.java
  doorip-api/src/main/java/org/doorip/auth/JwtAuthenticationFilter.java
  doorip-api/src/main/java/org/doorip/auth/UserAuthentication.java
  doorip-api/src/main/java/org/doorip/auth/UserId.java
  doorip-api/src/main/java/org/doorip/auth/UserIdArgumentResolver.java
  doorip-api/src/main/java/org/doorip/auth/config/SecurityConfig.java
  doorip-api/src/main/java/org/doorip/auth/config/WebConfig.java
  doorip-api/src/main/java/org/doorip/auth/jwt/JwtGenerator.java
  doorip-api/src/main/java/org/doorip/auth/jwt/JwtProvider.java
  doorip-api/src/main/java/org/doorip/auth/jwt/JwtValidator.java
  doorip-api/src/main/java/org/doorip/auth/jwt/Token.java
  doorip-api/src/main/java/org/doorip/common/Constants.java
  doorip-common/src/main/java/org/doorip/message/ErrorMessage.java
Labels: feat, 선웅

#7 [feat] 엔티티 클래스 매핑
  doorip-domain/src/main/java/org/doorip/todo/domain/Allocator.java
  doorip-domain/src/main/java/org/doorip/todo/domain/Progress.java
  doorip-domain/src/main/java/org/doorip/todo/domain/Secret.java
  doorip-domain/src/main/java/org/doorip/todo/domain/Todo.java
  doorip-domain/src/main/java/org/doorip/trip/domain/Participant.java
  doorip-domain/src/main/java/org/doorip/trip/domain/Role.java
  doorip-domain/src/main/java/org/doorip/trip/domain/Trip.java
  doorip-domain/src/main/java/org/doorip/user/domain/Platform.java
  doorip-domain/src/main/java/org/doorip/user/domain/User.java
Labels: feat, 선웅

#10 [chore] 데이터베이스 마이그레이션 flyway 라이브러리 적용
  doorip-api/build.gradle
  doorip-api/src/main/resources/db/migration/V1__ddl.sql
  doorip-domain/src/main/java/org/doorip/trip/domain/Participant.java
  doorip-domain/src/main/java/org/doorip/trip/domain/Trip.java
Labels: chore, 선웅

#13 [fix] cicd workflow 수정
  .github/workflows/ci-dev.yml
  .github/workflows/cicd-dev.yml
Labels: fix, 선웅

#12 [feat] 소셜 로그인 OpenFeign 관련 세팅
  doorip-common/src/main/java/org/doorip/message/ErrorMessage.java
  doorip-external/build.gradle
  doorip-external/src/main/java/org/doorip/config/FeignClientConfig.java
  doorip-external/src/main/java/org/doorip/openfeign/apple/AppleFeignClient.java
  doorip-external/src/main/java/org/doorip/openfeign/apple/AppleIdentityTokenParser.java
  doorip-external/src/main/java/org/doorip/openfeign/apple/AppleIdentityTokenValidator.java
  doorip-external/src/main/java/org/doorip/openfeign/apple/AppleOAuthProvider.java
  doorip-external/src/main/java/org/doorip/openfeign/apple/ApplePublicKey.java
  doorip-external/src/main/java/org/doorip/openfeign/apple/ApplePublicKeyGenerator.java
  doorip-external/src/main/java/org/doorip/openfeign/apple/ApplePublicKeys.java
  doorip-external/src/main/java/org/doorip/openfeign/kakao/KakaoAccessToken.java
  doorip-external/src/main/java/org/doorip/openfeign/kakao/KakaoAccessTokenInfo.java
  doorip-external/src/main/java/org/doorip/openfeign/kakao/KakaoFeignClient.java
  doorip-external/src/main/java/org/doorip/openfeign/kakao/KakaoOAuthProvider.java
Labels: feat, 정원

#15 [feat] 소셜 로그인 API 구현
  doorip-api/src/main/java/org/doorip/user/api/UserApiController.java
  doorip-api/src/main/java/org/doorip/user/dto/request/UserSignInRequest.java
  doorip-api/src/main/java/org/doorip/user/dto/response/UserResponse.java
  doorip-api/src/main/java/org/doorip/user/service/UserService.java
  doorip-common/src/main/java/org/doorip/message/ErrorMessage.java
  doorip-domain/build.gradle
  doorip-domain/src/main/java/org/doorip/user/domain/Platform.java
  doorip-domain/src/main/java/org/doorip/user/domain/RefreshToken.java
  doorip-domain/src/main/java/org/doorip/user/domain/User.java
  doorip-domain/src/main/java/org/doorip/user/repository/RefreshTokenRepository.java
  doorip-domain/src/main/java/org/doorip/user/repository/UserRepository.java
Labels: feat, 정원

#17 [feat] 회원가입 API 구현
  doorip-api/src/main/java/org/doorip/user/api/UserApiController.java
  doorip-api/src/main/java/org/doorip/user/dto/request/UserSignUpRequest.java
  doorip-api/src/main/java/org/doorip/user/service/UserService.java
  doorip-domain/src/main/java/org/doorip/user/domain/User.java
Labels: feat, 정원

#21 [feat] 로그아웃 API 구현
  doorip-api/src/main/java/org/doorip/user/api/UserApiController.java
  doorip-api/src/main/java/org/doorip/user/service/UserService.java
Labels: feat, 정원

#22 [feat] 회원 탈퇴 API 구현
  doorip-api/src/main/java/org/doorip/user/api/UserApiController.java
  doorip-api/src/main/java/org/doorip/user/service/UserService.java
Labels: feat, 정원

#24 [chore] Swagger 세팅
  doorip-api/build.gradle
  doorip-api/src/main/java/org/doorip/auth/config/SecurityConfig.java
  doorip-api/src/main/java/org/doorip/common/HealthCheckApiController.java
  doorip-api/src/main/java/org/doorip/config/SwaggerConfig.java
Labels: chore, 선웅

#25 [feat] Jwt 재발급 API 구현
  doorip-api/src/main/java/org/doorip/user/api/UserApiController.java
  doorip-api/src/main/java/org/doorip/user/dto/request/UserReissueRequest.java
  doorip-api/src/main/java/org/doorip/user/service/UserService.java
  doorip-common/src/main/java/org/doorip/message/ErrorMessage.java
Labels: feat, 정원

#29 [feat] 여행 대시보드 전체 조회 API 구현
  doorip-api/src/main/java/org/doorip/common/Constants.java
  doorip-api/src/main/java/org/doorip/trip/api/TripApiController.java
  doorip-api/src/main/java/org/doorip/trip/dto/response/TripGetResponse.java
  doorip-api/src/main/java/org/doorip/trip/dto/response/TripResponse.java
  doorip-api/src/main/java/org/doorip/trip/service/TripService.java
  doorip-api/src/main/resources/db/migration/V2__ddl.sql
  doorip-common/src/main/java/org/doorip/message/ErrorMessage.java
  doorip-domain/src/main/java/org/doorip/trip/repository/TripRepository.java
Labels: feat, 선웅

#32 [feat] 여행 TODO 생성 API 구현
  doorip-api/src/main/java/org/doorip/todo/api/TodoApiController.java
  doorip-api/src/main/java/org/doorip/todo/dto/request/TodoCreateRequest.java
  doorip-api/src/main/java/org/doorip/todo/service/TodoService.java
  doorip-api/src/main/resources/db/migration/V3__ddl.sql
  doorip-common/src/main/java/org/doorip/message/ErrorMessage.java
  doorip-domain/src/main/java/org/doorip/todo/domain/Allocator.java
  doorip-domain/src/main/java/org/doorip/todo/domain/Secret.java
  doorip-domain/src/main/java/org/doorip/todo/domain/Todo.java
  doorip-domain/src/main/java/org/doorip/todo/repository/TodoRepository.java
  doorip-domain/src/main/java/org/doorip/trip/domain/Participant.java
  doorip-domain/src/main/java/org/doorip/trip/domain/Trip.java
  doorip-domain/src/main/java/org/doorip/trip/repository/ParticipantRepository.java
Labels: feat, 선웅

#31 [feat] 여행 생성 API 구현
  doorip-api/src/main/java/org/doorip/trip/api/TripApiController.java
  doorip-api/src/main/java/org/doorip/trip/dto/request/TripCreateRequest.java
  doorip-api/src/main/java/org/doorip/trip/dto/response/TripCreateResponse.java
  doorip-api/src/main/java/org/doorip/trip/service/TripService.java
  doorip-common/src/main/java/org/doorip/message/ErrorMessage.java
  doorip-domain/src/main/java/org/doorip/trip/domain/Participant.java
  doorip-domain/src/main/java/org/doorip/trip/domain/Trip.java
  doorip-domain/src/main/java/org/doorip/trip/repository/TripRepository.java
Labels: feat, 정원

#33 [feat] 회원가입 중복 검증 로직 추가
  doorip-api/src/main/java/org/doorip/user/service/UserService.java
  doorip-common/src/main/java/org/doorip/message/ErrorMessage.java
  doorip-domain/src/main/java/org/doorip/user/repository/UserRepository.java
Labels: feat, 정원

#36 [chore] todo 도메인 -> trip 도메인으로 패키지 병합
  doorip-api/src/main/java/org/doorip/trip/api/TodoApiController.java
  doorip-api/src/main/java/org/doorip/trip/dto/request/TodoCreateRequest.java
  doorip-api/src/main/java/org/doorip/trip/service/TodoService.java
  doorip-domain/src/main/java/org/doorip/trip/domain/Allocator.java
  doorip-domain/src/main/java/org/doorip/trip/domain/Participant.java
  doorip-domain/src/main/java/org/doorip/trip/domain/Progress.java
  doorip-domain/src/main/java/org/doorip/trip/domain/Secret.java
  doorip-domain/src/main/java/org/doorip/trip/domain/Todo.java
  doorip-domain/src/main/java/org/doorip/trip/domain/Trip.java
  doorip-domain/src/main/java/org/doorip/trip/repository/TodoRepository.java
Labels: chore, 선웅

#39 [refactor] 여행 TODO 생성 API 리팩터링
  doorip-api/src/main/java/org/doorip/trip/api/TodoApiController.java
  doorip-api/src/main/java/org/doorip/trip/dto/request/TodoCreateRequest.java
  doorip-api/src/main/java/org/doorip/trip/service/TodoService.java
Labels: refactor, 선웅

#40 [feat] 프로필 조회 API 구현
  doorip-api/src/main/java/org/doorip/user/api/UserApiController.java
  doorip-api/src/main/java/org/doorip/user/dto/response/ProfileGetResponse.java
  doorip-api/src/main/java/org/doorip/user/service/UserService.java
  doorip-common/src/main/java/org/doorip/message/ErrorMessage.java
Labels: feat, 정원

#45 [feat] 로그인 성향 검사 검증 추가 구현
  doorip-api/src/main/java/org/doorip/user/service/UserService.java
Labels: feat, 정원

#46 [feat] 초대 코드 검증 API 구현
  doorip-api/src/main/java/org/doorip/trip/api/TripApiController.java
  doorip-api/src/main/java/org/doorip/trip/dto/request/TripVerifyRequest.java
  doorip-api/src/main/java/org/doorip/trip/service/TripService.java
  doorip-domain/src/main/java/org/doorip/trip/repository/TripRepository.java
Labels: feat, 정원

#47 [feat] 여행 TODO 전체 조회 API 구현
  doorip-api/src/main/java/org/doorip/common/Constants.java
  doorip-api/src/main/java/org/doorip/trip/api/TodoApiController.java
  doorip-api/src/main/java/org/doorip/trip/dto/response/TodoAllocatorResponse.java
  doorip-api/src/main/java/org/doorip/trip/dto/response/TodoGetResponse.java
  doorip-api/src/main/java/org/doorip/trip/service/TodoService.java
  doorip-api/src/main/java/org/doorip/trip/service/TripService.java
  doorip-domain/src/main/java/org/doorip/trip/domain/Secret.java
  doorip-domain/src/main/java/org/doorip/trip/repository/TodoRepository.java
Labels: feat, 선웅

#49 [feat] 여행 TODO 상세 조회 API 구현
  doorip-api/src/main/java/org/doorip/trip/api/TodoApiController.java
  doorip-api/src/main/java/org/doorip/trip/service/TodoService.java
  doorip-common/src/main/java/org/doorip/message/ErrorMessage.java
Labels: feat, 선웅

#51 [feat] 여행 TODO 삭제 API 구현
  doorip-api/src/main/java/org/doorip/trip/api/TodoApiController.java
  doorip-api/src/main/java/org/doorip/trip/service/TodoService.java
Labels: feat

#53 [feat] 여행 TODO 완료 & 미완료 API 구현
  doorip-api/src/main/java/org/doorip/trip/api/TodoApiController.java
  doorip-api/src/main/java/org/doorip/trip/service/TodoService.java
  doorip-domain/src/main/java/org/doorip/trip/domain/Todo.java
Labels: feat, 선웅

#55 [feat] 여행 입장 API 구현
  doorip-api/src/main/java/org/doorip/trip/api/TripApiController.java
  doorip-api/src/main/java/org/doorip/trip/dto/request/TripEntryRequest.java
  doorip-api/src/main/java/org/doorip/trip/dto/response/TripEntryResponse.java
  doorip-api/src/main/java/org/doorip/trip/service/TripService.java
  doorip-common/src/main/java/org/doorip/message/ErrorMessage.java
  doorip-domain/src/main/java/org/doorip/trip/repository/ParticipantRepository.java
Labels: feat, 정원

#60 [fix] 로그인 성향 결과 값 반환 오류 수정
  doorip-api/src/main/java/org/doorip/user/api/UserApiController.java
  doorip-api/src/main/java/org/doorip/user/dto/response/UserSignInResponse.java
  doorip-api/src/main/java/org/doorip/user/service/UserService.java
Labels: fix, 정원

#61 [feat] 여행 My TODO 상세 조회 API 구현
  doorip-api/src/main/java/org/doorip/trip/api/TripApiController.java
  doorip-api/src/main/java/org/doorip/trip/dto/response/MyTodoResponse.java
  doorip-api/src/main/java/org/doorip/trip/service/TripDetailService.java
  doorip-domain/src/main/java/org/doorip/trip/domain/Secret.java
  doorip-domain/src/main/java/org/doorip/trip/repository/TodoRepository.java
Labels: feat, 선웅

#66 [chore] User 엔티티 성향 테스트 결과 속성 타입 변경
  doorip-api/src/main/java/org/doorip/user/dto/response/ProfileGetResponse.java
  doorip-api/src/main/resources/db/migration/V4__ddl.sql
  doorip-domain/src/main/java/org/doorip/user/domain/User.java
Labels: chore, 선웅

#68 [feat] 클라이언트 요청 사항에 따른 API 공통 응답 스펙 변경
  doorip-api/src/main/java/org/doorip/common/ApiResponse.java
  doorip-common/src/main/java/org/doorip/message/SuccessMessage.java
Labels: feat, 선웅

#69 [chore] Todo 엔티티 마감일 속성 not null 설정
  doorip-domain/src/main/java/org/doorip/trip/domain/Todo.java
Labels: chore, 선웅

#70 [fix] 날짜 형식 변경
  doorip-api/src/main/java/org/doorip/trip/dto/request/TodoCreateRequest.java
  doorip-api/src/main/java/org/doorip/trip/dto/request/TripCreateRequest.java
  doorip-api/src/main/java/org/doorip/trip/dto/response/TodoGetResponse.java
  doorip-api/src/main/java/org/doorip/trip/dto/response/TripCreateResponse.java
  doorip-api/src/main/java/org/doorip/trip/dto/response/TripResponse.java
Labels: fix, 선웅

#72 [feat] 스플래쉬 분기 처리 API 구현
  doorip-api/src/main/java/org/doorip/user/api/UserApiController.java
  doorip-api/src/main/java/org/doorip/user/service/UserService.java
Labels: feat, 선웅

#75 [fix] Period.Between 메서드 날짜 계산 오류 해결
  doorip-api/src/main/java/org/doorip/trip/dto/response/TripCreateResponse.java
  doorip-api/src/main/java/org/doorip/trip/dto/response/TripResponse.java
Labels: fix, 선웅

#67 [feat] 프로필 성향 테스트 API 구현
  doorip-api/src/main/java/org/doorip/user/api/UserApiController.java
  doorip-api/src/main/java/org/doorip/user/dto/request/ResultUpdateRequest.java
  doorip-api/src/main/java/org/doorip/user/dto/response/ProfileGetResponse.java
  doorip-api/src/main/java/org/doorip/user/service/UserService.java
  doorip-common/src/main/java/org/doorip/message/ErrorMessage.java
  doorip-domain/src/main/java/org/doorip/user/domain/MappingIndex.java
  doorip-domain/src/main/java/org/doorip/user/domain/Result.java
  doorip-domain/src/main/java/org/doorip/user/domain/User.java
Labels: feat, 정원

#76 [feat] 여행 Our TODO 상세 조회 API 구현
  doorip-api/src/main/java/org/doorip/trip/api/TripApiController.java
  doorip-api/src/main/java/org/doorip/trip/dto/response/OurTodoResponse.java
  doorip-api/src/main/java/org/doorip/trip/dto/response/TripParticipantResponse.java
  doorip-api/src/main/java/org/doorip/trip/service/TripDetailService.java
  doorip-common/src/main/java/org/doorip/message/ErrorMessage.java
Labels: feat, 선웅

#77 [feat] 여행 친구 전체 조회 API 구현
  doorip-api/src/main/java/org/doorip/common/Constants.java
  doorip-api/src/main/java/org/doorip/trip/api/TripApiController.java
  doorip-api/src/main/java/org/doorip/trip/dto/response/TripParticipantGetResponse.java
  doorip-api/src/main/java/org/doorip/trip/dto/response/TripStyleResponse.java
  doorip-api/src/main/java/org/doorip/trip/service/TripDetailService.java
Labels: feat, 선웅

#79 [fix] 여행 TODO 상세 조회 DTO 스펙 수정
  doorip-api/src/main/java/org/doorip/trip/api/TodoApiController.java
  doorip-api/src/main/java/org/doorip/trip/dto/response/TodoDetailGetResponse.java
  doorip-api/src/main/java/org/doorip/trip/service/TodoService.java
Labels: fix, 선웅

#81 [fix] 애플 로그인 public key 관련 오류 수정
  doorip-external/src/main/java/org/doorip/openfeign/apple/ApplePublicKeys.java
Labels: fix, 정원

#85 [refactor] 여행 친구 전체 조회 비즈니스 로직 리팩터링
  doorip-api/src/main/java/org/doorip/common/Constants.java
  doorip-api/src/main/java/org/doorip/trip/service/TripDetailService.java
Labels: refactor, 선웅

#87 [fix] 여행 My TODO 개수 조회 쿼리 오류 수정
  doorip-api/src/main/java/org/doorip/trip/api/TripApiController.java
  doorip-api/src/main/java/org/doorip/trip/service/TripDetailService.java
  doorip-domain/src/main/java/org/doorip/trip/repository/TodoRepository.java
Labels: fix, 선웅

#89 [fix] 여행 My TODO 상세 정보 조회 API 스펙 변경
  doorip-api/src/main/java/org/doorip/trip/dto/response/MyTodoResponse.java
  doorip-api/src/main/java/org/doorip/trip/service/TripDetailService.java
Labels: fix, 선웅

#92 [chore] 여행 TODO 관련 Swagger 설정
  doorip-api/src/main/java/org/doorip/auth/ExceptionHandlerFilter.java
  doorip-api/src/main/java/org/doorip/auth/JwtAuthenticationEntryPoint.java
  doorip-api/src/main/java/org/doorip/common/ApiResponseUtil.java
  doorip-api/src/main/java/org/doorip/common/BaseResponse.java
  doorip-api/src/main/java/org/doorip/common/GlobalExceptionHandler.java
  doorip-api/src/main/java/org/doorip/config/SwaggerConfig.java
  doorip-api/src/main/java/org/doorip/trip/api/TodoApi.java
  doorip-api/src/main/java/org/doorip/trip/api/TodoApiController.java
  doorip-api/src/main/java/org/doorip/trip/api/TripApiController.java
  doorip-api/src/main/java/org/doorip/user/api/UserApiController.java
Labels: chore, 선웅

#97 [fix] 오류 메시지 코드 오타 수정
  doorip-common/src/main/java/org/doorip/message/ErrorMessage.java
Labels: fix, 선웅

#99 [fix] 여행 Our TODO 상세 조회 진행률 오류 수정
  doorip-api/src/main/java/org/doorip/trip/service/TripDetailService.java
  doorip-domain/src/main/java/org/doorip/trip/repository/TodoRepository.java
Labels: fix, 선웅

#101 [chore] 운영 서버 ci/cd workflow 설정
  .github/workflows/ci-prod.yml
  .github/workflows/cicd-prod.yml
Labels: chore, 선웅

#106 [fix] 운영 서버 ci/cd workflow 오류 수정
  .github/workflows/ci-prod.yml
  .github/workflows/cicd-prod.yml
Labels: fix, 선웅

#108 [chore] v1.0.0 -> v1.0.1 hotfix 수정 내용 동기화
  .github/workflows/ci-prod.yml
  .github/workflows/cicd-prod.yml
Labels: chore, 선웅

#110 [fix] 여행 입장 최대 인원 검증 로직 오류 수정
  doorip-api/src/main/java/org/doorip/trip/service/TripService.java
  doorip-common/src/main/java/org/doorip/message/ErrorMessage.java
Labels: fix, 선웅

#114 [release] v1.0.2 릴리즈
  README.md
  doorip-api/src/main/java/org/doorip/trip/service/TripService.java
  doorip-api/src/main/resources/db/migration/V5__ddl.sql
  doorip-common/src/main/java/org/doorip/message/ErrorMessage.java
Labels: 선웅, 정원, release

#116 [fix] 여행 참여자 성향 검사 결과 평균값 오류 수정
  doorip-api/src/main/java/org/doorip/trip/service/TripDetailService.java
Labels: fix, 선웅

#118 [release] v1.0.3 릴리즈
  doorip-api/src/main/java/org/doorip/trip/service/TripDetailService.java
Labels: 선웅, release
