Repository Team-Going/Going-Server, pull requests merged in 2024-03, with the labels that each got.

#126 [feat] 여행 나가기 API 구현
  doorip-api/src/main/java/org/doorip/common/Constants.java
  doorip-api/src/main/java/org/doorip/trip/api/TripApiController.java
  doorip-api/src/main/java/org/doorip/trip/service/TodoService.java
  doorip-api/src/main/java/org/doorip/trip/service/TripDetailService.java
  doorip-domain/src/main/java/org/doorip/trip/repository/ParticipantRepository.java
  doorip-domain/src/main/java/org/doorip/trip/repository/TodoRepository.java
Labels: feat, 선웅

#128 [feat] 프로필 수정 API 구현
  doorip-api/src/main/java/org/doorip/user/api/UserApiController.java
  doorip-api/src/main/java/org/doorip/user/dto/request/ProfileUpdateRequest.java
  doorip-api/src/main/java/org/doorip/user/service/UserService.java
  doorip-domain/src/main/java/org/doorip/user/domain/User.java
Labels: feat, 정원

#130 [fix] API 경로 중복 오류 수정
  doorip-api/src/main/java/org/doorip/trip/api/TripApiController.java
Labels: fix, 선웅

#132 [feat] 여행 성향 테스트 수정 API 구현
  doorip-api/src/main/java/org/doorip/trip/api/TripApiController.java
  doorip-api/src/main/java/org/doorip/trip/dto/request/ParticipantUpdateRequest.java
  doorip-api/src/main/java/org/doorip/trip/service/TripDetailService.java
  doorip-domain/src/main/java/org/doorip/trip/domain/Participant.java
Labels: feat, 정원

#137 [feat] 여행 TODO 생성 API 스펙 및 비즈니스 로직 변경
  doorip-api/src/main/java/org/doorip/trip/api/TodoApi.java
  doorip-api/src/main/java/org/doorip/trip/api/TodoApiController.java
  doorip-api/src/main/java/org/doorip/trip/service/TodoService.java
  doorip-common/src/main/java/org/doorip/message/ErrorMessage.java
Labels: feat, 선웅

#139 [feat] 개별 프로필 조회 API 구현
  doorip-api/src/main/java/org/doorip/trip/api/TripApiController.java
  doorip-api/src/main/java/org/doorip/trip/dto/response/TripParticipantProfileResponse.java
  doorip-api/src/main/java/org/doorip/trip/service/TripDetailService.java
Labels: feat, 정원

#141 [feat] 여행 TODO 수정 API 구현
  doorip-api/src/main/java/org/doorip/trip/api/TodoApi.java
  doorip-api/src/main/java/org/doorip/trip/api/TodoApiController.java
  doorip-api/src/main/java/org/doorip/trip/dto/request/TodoCreateAndUpdateRequest.java
  doorip-api/src/main/java/org/doorip/trip/service/TodoService.java
  doorip-domain/src/main/java/org/doorip/trip/domain/Todo.java
  doorip-domain/src/main/java/org/doorip/trip/repository/AllocatorRepository.java
Labels: feat, 선웅

#144 [feat] 여행 정보 조회 API 구현
  doorip-api/src/main/java/org/doorip/trip/api/TripApiController.java
  doorip-api/src/main/java/org/doorip/trip/dto/response/TripGetResponse.java
  doorip-api/src/main/java/org/doorip/trip/dto/response/TripsGetResponse.java
  doorip-api/src/main/java/org/doorip/trip/service/TripService.java
Labels: feat, 정원

#147 [feat] 여행 친구 전체 조회 API 스펙 및 비즈니스 로직 변경
  doorip-api/src/main/java/org/doorip/trip/actor/TripTendencyTestActor.java
  doorip-api/src/main/java/org/doorip/trip/actor/TripTendencyTestResult.java
  doorip-api/src/main/java/org/doorip/trip/dto/response/TripParticipantGetResponse.java
  doorip-api/src/main/java/org/doorip/trip/dto/response/TripParticipantResponse.java
  doorip-api/src/main/java/org/doorip/trip/dto/response/TripStyleResponse.java
  doorip-api/src/main/java/org/doorip/trip/service/TripDetailService.java
Labels: feat, 선웅

#145 [refactor] 개별 프로필 조회 비즈니스 로직 리팩터링
  doorip-api/src/main/java/org/doorip/trip/service/TripDetailService.java
  doorip-domain/src/main/java/org/doorip/user/domain/Result.java
Labels: refactor, 정원

#150 [fix] 여행 나가기 API 오류 수정
  doorip-api/src/main/java/org/doorip/trip/service/TripDetailService.java
  doorip-domain/src/main/java/org/doorip/trip/repository/ParticipantRepository.java
  doorip-domain/src/main/java/org/doorip/trip/repository/TodoRepository.java
Labels: fix, 선웅

#152 [fix] 여행 친구 전체 조회 API 스펙 변경
  doorip-api/src/main/java/org/doorip/common/Constants.java
  doorip-api/src/main/java/org/doorip/trip/actor/TripTendencyTestActor.java
  doorip-api/src/main/java/org/doorip/trip/actor/TripTendencyTestResult.java
  doorip-api/src/main/java/org/doorip/trip/dto/response/TripParticipantGetResponse.java
  doorip-api/src/main/java/org/doorip/trip/dto/response/TripStyleResponse.java
  doorip-api/src/main/java/org/doorip/trip/service/TripDetailService.java
Labels: fix, 선웅
